-- Typed models for the GithubRest SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Branch
---@field commit? table
---@field name? string
---@field protected? boolean

---@class BranchListMatch
---@field owner string
---@field repo string

---@class Commit
---@field author? table
---@field commit? table
---@field committer? table
---@field html_url? string
---@field node_id? string
---@field sha? string
---@field url? string

---@class CommitListMatch
---@field owner string
---@field repo string

---@class Gist
---@field created_at? string
---@field description? string
---@field files table
---@field html_url? string
---@field id? string
---@field node_id? string
---@field owner? table
---@field public? boolean
---@field updated_at? string
---@field url? string

---@class GistListMatch
---@field created_at? string
---@field description? string
---@field files? table
---@field html_url? string
---@field id? string
---@field node_id? string
---@field owner? table
---@field public? boolean
---@field updated_at? string
---@field url? string

---@class GistCreateData
---@field created_at? string
---@field description? string
---@field files table
---@field html_url? string
---@field id? string
---@field node_id? string
---@field owner? table
---@field public? boolean
---@field updated_at? string
---@field url? string

---@class Issue
---@field assignee? any
---@field assignees? table
---@field body? string
---@field closed_at? string
---@field comments? number
---@field created_at? string
---@field html_url? string
---@field id? number
---@field labels? table
---@field milestone? table
---@field node_id? string
---@field number? number
---@field state? string
---@field title? string
---@field updated_at? string
---@field url? string
---@field user? table

---@class IssueLoadMatch
---@field id number
---@field owner string
---@field repo string

---@class IssueListMatch
---@field owner string
---@field repo string

---@class IssueCreateData
---@field owner string
---@field repo string
---@field assignee? any
---@field assignees? table
---@field body? string
---@field closed_at? string
---@field comments? number
---@field created_at? string
---@field html_url? string
---@field id? number
---@field labels? table
---@field milestone? table
---@field node_id? string
---@field number? number
---@field state? string
---@field title? string
---@field updated_at? string
---@field url? string
---@field user? table

---@class IssueUpdateData
---@field id number
---@field owner string
---@field repo string
---@field assignee? any
---@field assignees? table
---@field body? string
---@field closed_at? string
---@field comments? number
---@field created_at? string
---@field html_url? string
---@field labels? table
---@field milestone? table
---@field node_id? string
---@field number? number
---@field state? string
---@field title? string
---@field updated_at? string
---@field url? string
---@field user? table

---@class Notification
---@field id? string
---@field last_read_at? string
---@field reason? string
---@field repository? table
---@field subject? table
---@field unread? boolean
---@field updated_at? string
---@field url? string

---@class NotificationListMatch
---@field id? string
---@field last_read_at? string
---@field reason? string
---@field repository? table
---@field subject? table
---@field unread? boolean
---@field updated_at? string
---@field url? string

---@class Org
---@field avatar_url? string
---@field blog? string
---@field created_at? string
---@field description? string
---@field email? string
---@field followers? number
---@field following? number
---@field html_url? string
---@field id? number
---@field location? string
---@field login? string
---@field name? string
---@field node_id? string
---@field public_gists? number
---@field public_repos? number
---@field updated_at? string
---@field url? string

---@class OrgLoadMatch
---@field id string

---@class Pull
---@field base? table
---@field body? string
---@field closed_at? string
---@field created_at? string
---@field draft? boolean
---@field head? table
---@field html_url? string
---@field id? number
---@field merged_at? string
---@field node_id? string
---@field number? number
---@field state? string
---@field title? string
---@field updated_at? string
---@field url? string
---@field user? table

---@class PullLoadMatch
---@field id number
---@field owner string
---@field repo string

---@class PullListMatch
---@field owner string
---@field repo string

---@class PullCreateData
---@field owner string
---@field repo string
---@field base? table
---@field body? string
---@field closed_at? string
---@field created_at? string
---@field draft? boolean
---@field head? table
---@field html_url? string
---@field id? number
---@field merged_at? string
---@field node_id? string
---@field number? number
---@field state? string
---@field title? string
---@field updated_at? string
---@field url? string
---@field user? table

---@class RateLimit
---@field rate? table
---@field resources? table

---@class RateLimitLoadMatch
---@field rate? table
---@field resources? table

---@class Repo
---@field avatar_url? string
---@field bio? string
---@field blog? string
---@field company? string
---@field created_at? string
---@field default_branch? string
---@field description? string
---@field email? string
---@field followers? number
---@field following? number
---@field fork? boolean
---@field forks_count? number
---@field full_name? string
---@field html_url? string
---@field id? number
---@field language? string
---@field location? string
---@field login? string
---@field name? string
---@field node_id? string
---@field open_issues_count? number
---@field owner? table
---@field private? boolean
---@field public_gists? number
---@field public_repos? number
---@field pushed_at? string
---@field size? number
---@field stargazers_count? number
---@field type? string
---@field updated_at? string
---@field url? string
---@field visibility? string
---@field watchers_count? number

---@class RepoLoadMatch
---@field owner string
---@field repo string

---@class RepoListMatch
---@field username string

---@class Search
---@field assignee? any
---@field assignees? table
---@field body? string
---@field closed_at? string
---@field comments? number
---@field created_at? string
---@field default_branch? string
---@field description? string
---@field fork? boolean
---@field forks_count? number
---@field full_name? string
---@field html_url? string
---@field id? number
---@field labels? table
---@field language? string
---@field milestone? table
---@field name? string
---@field node_id? string
---@field number? number
---@field open_issues_count? number
---@field owner? table
---@field private? boolean
---@field pushed_at? string
---@field size? number
---@field stargazers_count? number
---@field state? string
---@field title? string
---@field updated_at? string
---@field url? string
---@field user? table
---@field visibility? string
---@field watchers_count? number

---@class SearchListMatch
---@field assignee? any
---@field assignees? table
---@field body? string
---@field closed_at? string
---@field comments? number
---@field created_at? string
---@field default_branch? string
---@field description? string
---@field fork? boolean
---@field forks_count? number
---@field full_name? string
---@field html_url? string
---@field id? number
---@field labels? table
---@field language? string
---@field milestone? table
---@field name? string
---@field node_id? string
---@field number? number
---@field open_issues_count? number
---@field owner? table
---@field private? boolean
---@field pushed_at? string
---@field size? number
---@field stargazers_count? number
---@field state? string
---@field title? string
---@field updated_at? string
---@field url? string
---@field user? table
---@field visibility? string
---@field watchers_count? number

---@class User
---@field avatar_url? string
---@field bio? string
---@field blog? string
---@field company? string
---@field created_at? string
---@field email? string
---@field followers? number
---@field following? number
---@field html_url? string
---@field id? number
---@field location? string
---@field login? string
---@field name? string
---@field node_id? string
---@field public_gists? number
---@field public_repos? number
---@field type? string
---@field updated_at? string
---@field url? string

---@class UserLoadMatch
---@field id string

local M = {}

return M
